[env]
TERM = "xterm-256color"

[font]
size = 11.00

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
decorations = "None"
dynamic_padding = true
opacity =  0.95
startup_mode = "Maximized"

[window.padding]
x = 15
y = 15

[terminal.shell]
program = "wsl"
args = [
        "-d",
        "Ubuntu-24.04",
        "--cd",
        "~"
]
