[env]
TERM = "xterm-256color"

[font]
size = 11.00

normal.family = "FiraCode Nerd Font"
normal.style = "Regular"

[window]
padding.x = 15
padding.y = 15

decorations = "None"
dynamic_padding = true
opacity =  0.95
startup_mode = "Maximized"

[terminal.shell]
program = "wsl"
args = [
        "-d",
        "Ubuntu-24.04",
        "--cd",
        "~"
]