[env]
TERM = "xterm-256color"

[font]
normal.family = "FiraCode Nerd Font"
normal.style = "Regular"
size = 10.00

[cursor]
style.shape = "Block" # Block|Underline|Beam
style.blinking = "Always"  # Never|Off|On|Always
blink_interval = 500  # milliseconds

[window]
padding.x = 10
padding.y = 10

#decorations = "None"
dynamic_padding = true
opacity =  0.95
startup_mode = "Maximized"

# For WSL
[terminal.shell]
program = "wsl"
args = [
        "-d",
        "Ubuntu",
        "--cd",
        "~"
]
