[env]
TERM = "xterm-256color"

[font]
normal.family = "FiraCode Nerd Font"
normal.style = "Regular"
size = 11.00

[cursor]
style.shape = "Beam"

[window]
padding.x = 15
padding.y = 15

decorations = "None"
dynamic_padding = true
opacity =  0.95
startup_mode = "Maximized"

# For WSL
#[terminal.shell]
#program = "wsl"
#args = [
#        "-d",
#        "Ubuntu-24.04",
#        "--cd",
#        "~"
#]
